services:

  app:
    build: 
      context: .
      target: development
    container_name: api-container-dev
    ports:
      - "9880:9880"     
    volumes:
      - .:/app                       # Map local code to container
      - /app/node_modules            # Anonymous volume to protect container's node_modules
      - ./logs/:/app/logs            # if logs are given
    env_file:
      - ${ENV_PATH:-./.env}
    # depends_on:
    #   - if depends on any
    networks:
      - network-name
  